### ISSUE TITLE
Feature Request: "No VR mode" that reverts the client back to normal Quake display/HUD/weapon placement mode

### ISSUE THREAD

**Issue by cplemaster** [vittorioromeo/quakevr#41]
I am aware that there is a "FakeVR" mode for playing without a headset, however I don't find it all that great for actually playing, I typically just use it to test changes in the game or debug connection issues with friends.

Is there a possibility to have a NoVR mode that reverts the game back to "flat mode" Quake, just like a normal sourceport? My main use case would be for players who don't have VR headsets to play the game, however without any VR hands and body or dual wielding (unfortunately)

You could possibly enable weapon pickups with Instant force grab with just a button-press, so this function is maintained?

**Comment by SuperV1234** [comment]
It's a bit out of scope for the project. I guess the way forward would be to make the FakeVR mode fully playable, but that is not a priority.
