### ISSUE TITLE
When will the next version be released

### ISSUE THREAD

**Issue by GenericJohnDoeNO0** [vittorioromeo/quakevr#56]
Hi there, i do not want to nag around but will there be a new version for pcvr? Or was this project abandoned?

**Comment by GenericJohnDoeNO0** [comment]
Aaaaand it is abandoned.

**Comment by vittorioromeo** [comment]
Not abandoned and I don't appreciate issues like these.

1. It's a hobby project that I make no profit off and I work in my spare time. Either be patient, **or contribute**.

2. It takes a few seconds to verify that development is happening on a separate branch: https://github.com/vittorioromeo/quakevr/tree/develop
