### ISSUE TITLE
Crash with Horn of Conjuring in Scourge of Armagon

### ISSUE THREAD

**Issue by codeflorist** [vittorioromeo/quakevr#58]
picking up a Horn of Conjouring in Scource of Armagon crashes the game with
```
NULL function
Host_Error: Program error
```
there is one in e2m1 (Ancient Realms)

**Comment by codeflorist** [comment]
this is actually a gamebreaking bug, since one cannot continue without picking up the horn in HIP2M3 The Catacombs

**Comment by codeflorist** [comment]
it is working with v0.0.5, so the bug must have been introduced in v0.0.5.1

**Comment by codeflorist** [comment]
the crash only occurs, if "Body Item Interactions" is set to "on" in the Immersion Settings

**Comment by vittorioromeo** [comment]
Sorry for the issue! Thanks for the report -- can you confirm that temporarily setting "Body Item Interactions" to OFF is a valid workaround?

**Comment by codeflorist** [comment]
Yes, that's working.

PS: Many many thanks Vittorio for this great experience! :D

**Comment by vittorioromeo** [comment]
Fixed for next version
