### ISSUE TITLE
Nail Traps are bugged in Dissolution of Eternity

### ISSUE THREAD

**Issue by codeflorist** [vittorioromeo/quakevr#65]
Nail traps in Dissolution of Eternity seem to shoot rockets instead of nails, which explode immediately in their sockets, creating a deadly blast. Thus many sections can only be passed by turning on God Mode.

An example would be in R1M7: Tomb of the Overlord (see https://www.youtube.com/watch?v=j5YbROf9ozo at 1:46). There are many more nail traps in e.g. R2M4: Curse of Osiris or R2M5: Wizard's Keep.

The bug happens in v0.0.5.1 as well as v0.0.7.0 beta#1.

**Comment by vittorioromeo** [comment]
Fixed for the next version.

**Comment by codeflorist** [comment]
Awesome, many thanks! :)
