### ISSUE TITLE
support for dimensions of the past and dimensions of the machine from quake remaster

### ISSUE THREAD

**Issue by powerpuffboysz** [vittorioromeo/quakevr#66]
Title

**Comment by vittorioromeo** [comment]
Dimensions of the Past works fine, you just have to download it and access the maps via the in-game menu. I haven't tried Dimensions of the Machine, but as long as it doesn't come with custom gameplay elements it should work as well.

**Comment by powerpuffboysz** [comment]
Coolio. Wasn't sure as the readme only states compatibility with base game, scourge, and dissolution.
